version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fh-get-user-notes"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-za3s9xxcisjk"
s3_prefix = "fh-get-user-notes"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
