AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  user-note-FH

  Sample SAM Template for user-note-FH

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  GetUserNoteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: handler/
      Handler: app.getUserNotes
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Architectures:
        - x86_64
      Events:
        userNote:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getUserNotes
            Method: post

  DynamodbUserNote:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: fh-user-notes
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
        - AttributeName: created_date
          AttributeType: S
      KeySchema:
        - AttributeName: user
          KeyType: HASH
        - AttributeName: created_date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DynamodbUTokenEmailLookup:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: fh-token-email-lookup
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: token
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

          


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetUserNotesApi:
    Description: "API Gateway endpoint URL for Prod stage for getUserNotes function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getUserNotes/"
  GetUserNoteFunction:
    Description: "getUserNotes Lambda Function ARN"
    Value: !GetAtt GetUserNoteFunction.Arn
  GetUserNoteFunctionIamRole:
    Description: "Implicit IAM Role created for getUserNotes function"
    Value: !GetAtt GetUserNoteFunction.Arn
